version: "2"

services:
  zk:
    image: bobrik/zookeeper
    network_mode: host
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1

  master:
    image: mesosphere/mesos-master:1.5.0
    network_mode: host
    environment:
      MESOS_ZK: zk://127.0.0.1:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
      MESOS_REGISTRY: replicated_log
      MESOS_HOSTNAME: ${DOCKER_IP}
      LIBPROCESS_IP: ${DOCKER_IP}
    depends_on:
      - zk

  agent:
    image: mesosphere/mesos-slave:1.5.0
    network_mode: host
    pid: host
    environment:
      MESOS_SYSTEMD_ENABLE_SUPPORT: "false"
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_HOSTNAME: ${DOCKER_IP}
      LIBPROCESS_IP: ${DOCKER_IP}
      MESOS_WORK_DIR: /tmp/mesos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk
      - master